# Site settings
title: dummey.github.io
email: dummey@gmail.com
description: "A collection of my adventures and accidents through life."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dummey.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  dummey

# Build settings
markdown: kramdown
